### ISSUE TITLE
Implement final text for copyright section

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#10]
Text: 
"Except where otherwise noted, content on this site is licensed under a Creative Commons Attribution 4.0 International License. Creative Commons Attribution 4.0 International License (Link: http://creativecommons.org/licenses/by/4.0/)"

**Comment by nilswindisch** [comment]
Wie ist der deutschsprachige Text?

**Comment by dbeucke** [comment]
Erstmal keine deutsche Übersetzung. Kann das im language file angepasst werden?
