### ISSUE TITLE
Generate list of departments

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#117]
We need this commit: https://github.com/LibreCat/LibreCat/issues/195
for correct number of publications in our department list.

**Comment by christianmahnke** [comment]
https://github.com/subugoe/pubdev_docker/blob/master/patches/9051departments.patch

**Comment by christianmahnke** [comment]
Just using this diff, doesn't help.

**Comment by christianmahnke** [comment]
We have it now as part of 0.5.2. this doesn't help since we currently don't have a direct connection between publication and department.

**Comment by dbeucke** [comment]
Last version in GitHub
https://github.com/subugoe/pubdev_docker/blob/master/department-goe.yml
