### ISSUE TITLE
Optimize forms

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#119]
The author field in publication form is small.

Do we need this grey box?

![bildschirmfoto 2017-03-13 um 15 17 17](https://cloud.githubusercontent.com/assets/4047340/23858327/577d009e-0800-11e7-83f0-ba2fe83c2506.png)

**Comment by nilswindisch** [comment]
"Do we need this grey box?" I don't know.

**Comment by dbeucke** [comment]
I don't need is - please delete it.
