### ISSUE TITLE
Test with facets

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#125]
We need changes in `config/feature.yml` to adapt filter in the facets. But also a restart of the server (I couldn't do this!).
We should test it.

**Comment by christianmahnke** [comment]
We need a list which facets will be needed. Here is a start https://github.com/subugoe/pubdev_docker/blob/master/patches/0031facet-features.diff

**Comment by dbeucke** [comment]
I wonder, why not all facets will be displayed. E.g. "Author".

But at the moment, it looks fine.
