### ISSUE TITLE
Mark/unmark function doesn't work

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#126]
The button is visible but nothing happen.

**Comment by nilswindisch** [comment]
I suspect this is related to LibreCat 0.5.1

The file frontend.js in 0.5.1 is different from 0.5.2

https://github.com/LibreCat/LibreCat/blob/0.5.1/public/javascripts/frontend.js
https://github.com/LibreCat/LibreCat/blob/0.5.2/public/javascripts/frontend.js

**Comment by nilswindisch** [comment]
Updating the file content seem to be not enough. No clue (at least for now) how much effort is needed to solve this.

**Comment by dbeucke** [comment]
Issue in LibreCat https://github.com/LibreCat/LibreCat/issues/221
