### ISSUE TITLE
Our embed function is different from LibreCat (demo)

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#130]
## Demo:
http://demo.librecat.org/person/1234?person=1234&style=apa
(strange why I get another person id if I switch to APA!)
`<div class="publ"><script type="text/javascript" charset="UTF-8" src="http://demo.librecat.org/embed?cql=person%3D1234&cql=person%3D1234&style=apa&fmt=js"></script><noscript><a href="http://demo.librecat.org/embed?cql=person%3D1234&cql=person%3D1234&style=apa" target="_blank">My Publication List</a></noscript></div>
`

## pub-dev:
https://pub-dev.sub.uni-goettingen.de/person/khoff1?style=apa
`<div class="publ"><script type="text/javascript" charset="UTF-8" src="https://pub-dev.sub.uni-goettingen.de/person/khoff1?style=apastyle=apa&cql=person%3Dkhoff1&fmt=js"></script><noscript><a href="https://pub-dev.sub.uni-goettingen.de/person/khoff1?style=apastyle=apa&cql=person%3Dkhoff1" target="_blank">My Publication List</a></noscript></div>`

**Comment by christianmahnke** [comment]
The problem is generated probably here:
https://github.com/LibreCat/LibreCat/blob/master/views/filters.tt#L187

**Comment by christianmahnke** [comment]
This Problem can be easily be reproduced by adding an alias to a user which contains letters and numbers. If you then use this alias to open the user page, the embed will break.

**Comment by christianmahnke** [comment]
https://github.com/LibreCat/LibreCat/pull/241
