### ISSUE TITLE
Add notification at author page

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#134]
Add a notification above A-Z - text will be delivered until Monday

**Comment by nilswindisch** [comment]
"notification" as in "hint, tip, note etc" or "you've got mail"?

**Comment by dbeucke** [comment]
A simple text. But I didn't want to write "add text" in every issue.

**Comment by nilswindisch** [comment]
the simpler the better. less room for misinterpretation.

**Comment by dbeucke** [comment]
Please add this text:
"By now, XXX authors are listed on individual author pages in GRO, with more to come.
Please use the character tabs for browsing through the available authors. Publication data in GRO stems from several sources such as author homepages, authoritative databases such as Web of Science or CrossRef and have been carefully curated by a library team. Authors on GRO can export their publication lists in multiple formats or embed the lists dynamically on external websites."

Use`[% stats.researchers %]` for XXX
