### ISSUE TITLE
Add eRA logo in footer

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#135]
Please add the eRA logo in the footer.

Logo line: Uni, SUB, eRA
second line: LibreCat (maybe centered)

Please feel free to find the best way.

I know, that this logo is not the best. Could you do something with it or do you need something totally different?
![era_adapted_large](https://cloud.githubusercontent.com/assets/4047340/24293697/63095908-1093-11e7-8bb4-6a89b58ba995.png)

**Comment by nilswindisch** [comment]
Could you please provide a SVG/EPS version.

**Comment by dbeucke** [comment]
Requested

**Comment by dbeucke** [comment]
[SVG.zip](https://github.com/subugoe/goefis/files/875999/SVG.zip)
