### ISSUE TITLE
The facet "indexed in" doesn't work

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#143]
The facet "indexed in" should count PubMed and WoS publications. This is not the case.

Maybe this is a LibreCat issue?

**Comment by christianmahnke** [comment]
Have this ever been the case? How about demo.librecat.org?
Maybe we rename it to remove the facet? ;)

**Comment by christianmahnke** [comment]
https://pub-dev.sub.uni-goettingen.de/publication
