### ISSUE TITLE
POST http://localhost:5001/marked_total 403 (Forbidden)

### ISSUE THREAD

**Issue by nilswindisch** [subugoe/goefis#21]
on start and other pages independent from being logged in or not.
<img width="1286" alt="screenshot 2016-10-24 11 20 51" src="https://cloud.githubusercontent.com/assets/914680/19640210/f8bad3e8-99db-11e6-88ad-63cf7d4d6052.png">
<img width="309" alt="screenshot 2016-10-24 11 21 31" src="https://cloud.githubusercontent.com/assets/914680/19640221/0936f6fc-99dc-11e6-9eb6-990bdaa72522.png">

**Comment by ArSa-Apps** [comment]
not sure about this one, but it says something about the "index:447", there is a ";" misplaced or something. Is there such a line in file "index"?

**Comment by nilswindisch** [comment]
that can be ignored in the context of this issue, it's a different unrelated bug.

calling http://localhost:5001/marked_total directly works fine, it's the "POST" and way through Dancer  that seems to be the Problem.
