### ISSUE TITLE
LDAP log in

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#48]
authentication to LibreCat with Uni Göttingen LDAP

**Comment by christianmahnke** [comment]
This will probably not be in place for the meeting on Monday. i've played around with the [new documentation](https://github.com/LibreCat/LibreCat/wiki/Import-Users) and already found two bugs in Librecat:
- [#154](https://github.com/LibreCat/LibreCat/issues/154)
- [#155](https://github.com/LibreCat/LibreCat/issues/155)
And another possible in Catmandu:
-  [#286](https://github.com/LibreCat/Catmandu/issues/286)

We could probably do something by hand, but I'm not satisfied doing the pre-alpha test work.

**Comment by dbeucke** [comment]
The bugs should be fixed before implement the feature. I agree, not doing the pre-alpha test work.

I will collect the list of initial users ( #74 ) and could add them manual.

**Comment by christianmahnke** [comment]
We are getting there quite slowly, I've hit another possible bug:
https://github.com/LibreCat/Catmandu-LDAP/issues/2

**Comment by christianmahnke** [comment]
The problems are solved to an large extend, there is a tool that extracts test users and transforms them to Yaml in `gro-data`.

**Comment by christianmahnke** [comment]
This is now active for http://pub-dev.sub.uni-goettingen.de/ 
It won't be integrated in the desktop aka development version of the Docker thing.
