### ISSUE TITLE
Fix JS embed file

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#50]
Fix export of JS file for embed function.

I suspect wrong line breaks could be the problem. See:
https://github.com/subugoe/goefis/commit/c5e60a5796ae4c291f91063eecaf665688475354

**Comment by nilswindisch** [comment]
There is no JS export. it would be very helpful if you could describe what's broken (actual vs. expected outcome).

If it's about the JS embed, the output works as expected comparing http://pub-dev.sub.uni-goettingen.de/publication?cql_query= with https://pub.uni-bielefeld.de/publication?q=&fmt=html#

**Comment by dbeucke** [comment]
I tested do embed JS in a TYPO3 site. Follow code was embeded:

> <script type="text/javascript" charset="UTF-8" src="http://pub-dev.sub.uni-goettingen.de/publication?q=author%3D21935&ftyp=js"></script>
> <script type="text/javascript" charset="UTF-8" src="http://pub-dev.sub.uni-goettingen.de/publication?q=type%3Dbook_chapter&ftyp=js"></script>
> <h1>Test</h1>
> 
> <script type="text/javascript" charset="UTF-8" src="https://pub.uni-bielefeld.de/publication?q=person%3D6591682&ftyp=js"></script>

And the pub-dev code is not shown in the site: https://dev.adw-goe.de/test/Test%20DAniel/
I see the following mistake:
<img width="1533" alt="bildschirmfoto 2016-11-29 um 12 27 40" src="https://cloud.githubusercontent.com/assets/4047340/20708205/43db9460-b62f-11e6-9283-e4f612dd6c63.png">

**Comment by nilswindisch** [comment]
judging from your screenshot the console shows 3 errors. Would be nice to know what errors.

**Comment by nilswindisch** [comment]
seems to be a bug not related to goefis, but LibreCat itself.

**Comment by dbeucke** [comment]
Was fixed in LibreCat
