### ISSUE TITLE
Replace "Bielefeld" with "Göttingen"

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#54]

**Comment by nilswindisch** [comment]
could you please be more specific there are quite a few issues that have to be treated with more attention.

https://github.com/LibreCat/LibreCat/search?q=bielefeld&utf8=%E2%9C%93

**Comment by nilswindisch** [comment]
@dbeucke wanna help? I managed to include the yml language files our layer and you could contribute if you want. Might be a good idea since you have a broader view on where edits are most urgent.
