### ISSUE TITLE
Replace "PUB" with "GRO"

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#55]

**Comment by nilswindisch** [comment]
Please be more specific. This are all matches of template files (.tt) where "pub" is used: https://github.com/LibreCat/LibreCat/search?p=1&q=pub+filename%3Att&type=Code&utf8=%E2%9C%93

**Comment by christianmahnke** [comment]
This doesn't really help since for example PubMedId also matches, we could try something like PUB[^\w]

**Comment by nilswindisch** [comment]
@dbeucke wanna help? I managed to include the yml language files our layer and you could contribute if you want. Might be a good idea since you have a broader view on where edits are most urgent.
