### ISSUE TITLE
Page Departments broken

### ISSUE THREAD

**Issue by nilswindisch** [subugoe/goefis#57]
When selecting "Departments" from the tabs on the start page. 

`{
   "error" : "Warning caught during route execution: Use of uninitialized value in numeric eq (==) at /srv/LibreCat/lib/LibreCat/App/Helper.pm line 698.\n",
   "exception" : "Warning caught during route execution: Use of uninitialized value in numeric eq (==) at /srv/LibreCat/lib/LibreCat/App/Helper.pm line 698.\n"
}`

**Comment by dbeucke** [comment]
non-reproducible with current version.
