### ISSUE TITLE
Choosing an alternative citation style on page "Marked Publications" jumps to start page

### ISSUE THREAD

**Issue by nilswindisch** [subugoe/goefis#58]

**Comment by dbeucke** [comment]
non-reproducible with current version.

BUT: If you chose another style and try to delet this filter, I will jump to start page.

**Comment by nilswindisch** [comment]
Please report it to LibreCat then.

**Comment by dbeucke** [comment]
see: https://github.com/LibreCat/LibreCat/issues/159
