### ISSUE TITLE
Embed function for GCMS and GöttingenCampus (TYPO3)

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#62]
The function from LibreCat (JS, iFrame) have to be run.

We should also ask @Najko for advise how they did it in Bielefeld.

**Comment by christianmahnke** [comment]
The iFrame stuff works with the pub-dev instance, maybe this might be enough for GCMS?

**Comment by dbeucke** [comment]
Mr Richter (PR Uni Göttingen) got an email with examples from Uni Bielefeld.

**Comment by dbeucke** [comment]
It works on localhost. See what happens with PI data on pub-dev.
