### ISSUE TITLE
brocken "GRO" link in publication list

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#63]
The "GRO" link in publication list doesn't work. 

It links to an IP adresse!?

<img width="881" alt="bildschirmfoto 2017-01-30 um 15 52 24" src="https://cloud.githubusercontent.com/assets/4047340/22427645/46541cac-e704-11e6-9502-2420527cb776.png">
<img width="423" alt="bildschirmfoto 2017-01-30 um 15 54 03" src="https://cloud.githubusercontent.com/assets/4047340/22427677/61e1449a-e704-11e6-9895-965e9b008bae.png">

**Comment by christianmahnke** [comment]
The Problem is in `views/links.tt`, we either could remove the host part, which will result in relative links, which is may be not was is intended here. But it should work for the start.

**Comment by christianmahnke** [comment]
Will be fixed with new deployment, there is a Patch for this. https://github.com/subugoe/pubdev_docker/blob/master/patches/fix-links.patch
@nilswindisch should be aware of this.

**Comment by dbeucke** [comment]
It works 👍
