### ISSUE TITLE
Enhance patch workflow

### ISSUE THREAD

**Issue by christianmahnke** [subugoe/goefis#65]
The current patch workflow works, but there are minor possible issues, these are for example that a developer currently can't see a fully patched system during the development process. Another possible issue might arrise if there are changes for different issues on the same file, this can result in a conflict.
This issue should integrate ``robonils.sh`` with the ``setup-dev.sh`` script to create such a fully patched version of either LibreCat or the layer. Second goal would be some sanity check for patches.

**Comment by dbeucke** [comment]
My local test run well.
