### ISSUE TITLE
Include CSL server in the Docker stuff

### ISSUE THREAD

**Issue by christianmahnke** [subugoe/goefis#66]
Include the citation style language related things.

**Comment by christianmahnke** [comment]
The first step is done, it is included in the Docker build, next step is configuration.

**Comment by christianmahnke** [comment]
The configuration now is also in place, the documentation in the [LibreCat Wiki](https://github.com/LibreCat/LibreCat/wiki/Citation-Style-Language) was updated.

**Comment by dbeucke** [comment]
Great. The test (https://github.com/LibreCat/LibreCat/wiki/Citation-Style-Language#using-librecat-to-test) with local system works :-)

@christianmahnke How will be the workflow to have the citation information in our system? Via import?

**Comment by dbeucke** [comment]
Could this be a problem? https://github.com/LibreCat/LibreCat/issues/156
