### ISSUE TITLE
Keep track of strings to be changed

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#68]
There is a need to keep the replace script up to date.

**Comment by dbeucke** [comment]
Words to replace:
* UniBi -> UniGoe (e.g. http://pub-dev.sub.uni-goettingen.de/librecat/admin/account/new)
* Publikationen an der Universität LibreCat --> Publikationen an der Universität Göttingen (http://pub-dev.sub.uni-goettingen.de/ - German page)

--> this changes are done

**Comment by dbeucke** [comment]
Please reopen if necessary.

**Comment by christianmahnke** [comment]
In http://pub-dev.sub.uni-goettingen.de/librecat/admin/account Is still a PEVZ ID thing visible.

**Comment by christianmahnke** [comment]
https://github.com/subugoe/pubdev_docker/blob/master/goettingenfy.py#L76
