### ISSUE TITLE
Remove "Data" tabs

### ISSUE THREAD

**Issue by nilswindisch** [subugoe/goefis#71]

**Comment by dbeucke** [comment]
It is deleted mostly everywhere. But I find it on the "Home" page.

![bildschirmfoto 2017-02-06 um 09 57 36](https://cloud.githubusercontent.com/assets/4047340/22640422/d67940b6-ec52-11e6-841c-2f5845ff9929.png)

**Comment by nilswindisch** [comment]
let's check that in/after our weekly.

**Comment by christianmahnke** [comment]
The remaining issue is caused by the way we create our layer. A patch is a plied to a clean source of LibreCat, the files which have differences will be copied into our layer, after that, the repository will be reverted for the next patch. Thus the patches currently are a bit to atomic. ;)

**Comment by nilswindisch** [comment]
ok, but didn't we agreed on keeping the patches as atomic as possible to avoid conflicts and _stack patches_ instead of applying them on a clean state of the LibreCat core?

**Comment by nilswindisch** [comment]
The patch works, so I'll transfer this issue to @christianmahnke because the problem ssems to be related to how the build process applies patches…

**Comment by nilswindisch** [comment]
Waiting for deploy/build workflow to apply working patches successfully
