### ISSUE TITLE
Get a complete list of initial users

### ISSUE THREAD

**Issue by christianmahnke** [subugoe/goefis#74]
Get a list with team members, editors and stake holders from SUB, maybe even GWDG and Controlling.

**Comment by dbeucke** [comment]
Add this users to GRO.

**Comment by dbeucke** [comment]
Start with a list (work in progress)
https://gitlab.gwdg.de/sub-gro/data/wikis/user-for-gro

**Comment by christianmahnke** [comment]
I've added the GWDG IDs
