### ISSUE TITLE
Make bibliographic data clickable

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#88]
By now, the bibliographic data have a hover effect and they change the color to green.

It should be clickable and link to the detail view.

**Comment by nilswindisch** [comment]
Seems like I'm not able to replicate the "change to color to green", please be more specific. Which site, logged in user or not etc.

**Comment by dbeucke** [comment]
OK. Not green, I mean grey.

It is in publication list. But it isn't work at current GRO version. You could see it at LibreCat demo.

<img width="1205" alt="bildschirmfoto 2017-02-13 um 21 21 24" src="https://cloud.githubusercontent.com/assets/4047340/22901639/a5cdc0b4-f232-11e6-87b4-628f31161db5.png">

<img width="1212" alt="bildschirmfoto 2017-02-13 um 12 37 16" src="https://cloud.githubusercontent.com/assets/4047340/22901658/ac1f2098-f232-11e6-9ce9-957e9af56c0d.png">

**Comment by christianmahnke** [comment]
We agreed at the daily we should ask the core team to address this, since we think other might want this as well. This should be an issue for LibreCat.
