### ISSUE TITLE
Implement logo in footer

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#9]
Logo (without headline): Uni Göttingen, SUB Göttingen

Logo with text: "Powered by" + Logo LibreCat

**Comment by nilswindisch** [comment]
"Powered by" wirklich? klingt sehr nach letztes Jahrtausend.

**Comment by nilswindisch** [comment]
@dbeucke Deutschsprachige Texte?

**Comment by nilswindisch** [comment]
@dbeucke was meint "(without headline)"?

**Comment by dbeucke** [comment]
"Powered by" nutzen die Bielefelder und die Gent-Leute. Daher habe ich das so übernommen. Mir ist es eigentlich egal. Es wäre dann einheitlich.

without headline meint, dass da nichts drüber stehen soll. Also nicht Support oder so

**Comment by dbeucke** [comment]
"Powered by" würde ich nicht übersetzten. Deutsch und Englisch gleich. 
Das könnte man/ich doch auch in der Language-Datei anpassen?!
