### ISSUE TITLE
Add text to start page

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#91]
Main text:
"Göttingen Research Online
Scientific communication takes place in publications and publications tell the profile of Göttingen Campus. What topics do our researchers work on, where do they publish and with whom? Learn more about the power of Göttingen Campus on our public research database Göttingen Research Online that contains information of xxx publications and yyy authors."
 
Text for three “boxes”

"Add your Research
Register with your university’s identity, find your publications imported from Web of Science or PubMed, and claim them with a click. Include new publications or projects, and monitor your personal information on your individual dashboard."

"Search for publications
Export publication lists for individuals, departments or schools, automatically update your publication lists on websites and for applications, follow up on citations and use in social media. Discover collaboration networks and research profiles. "

"Access without boundaries
Get directly to publications and data sets, download and reuse them directly. Find zzz Open Access publications from yyy authors and monitor the transition of Göttingen Campus to transparency and openness."

Images will follow

**Comment by nilswindisch** [comment]
Waiting for images

**Comment by nilswindisch** [comment]
Not sure where to get the information for "yyy authors". @dbeucke Please add another issue. Some coding might be required.

**Comment by nilswindisch** [comment]
@dbeucke please add another issue for the currently missing images.
