### ISSUE TITLE
Looking for missing images on start page

### ISSUE THREAD

**Issue by dbeucke** [subugoe/goefis#95]

**Comment by christianmahnke** [comment]
In which state are images missing? Do you have a screenshot?

**Comment by dbeucke** [comment]
Add your Research

![office-1209640](https://cloud.githubusercontent.com/assets/4047340/23366489/22e769d6-fd07-11e6-927b-7938f5686bfc.jpg)

**Comment by dbeucke** [comment]
Search for publications

![books-768426](https://cloud.githubusercontent.com/assets/4047340/23366509/3b3ae40e-fd07-11e6-8198-ccaa1407e1ee.jpg)
